### ISSUE TITLE
add setting `favoritesPanel.workspaceCommands`

### ISSUE THREAD

**Issue by GitMensch** [sabitovvt/vscode-favorites-panel#14]
I suggest to use the same separation as https://github.com/usernamehw/vscode-commands/ by splitting the setting configuration - `favoritesPanel.commands` would then only be working where it currently is defined - in user configuration - while then new `favoritesPanel.workspaceCommands` would only work when defined in workspace settings.

This would have the additional benefit that a "common" set can be configured in _possibly shared_ workspace configurations (especially run commands that are workspace specific like tests, server start, ...) while users can keep there general settings (especially editor related) in the user configuration.

After getting used to this in the other extension and seeing that user + workspace settings are the way to go (also with the option of settings sync between devices) I'm closing #11 in favor of this.

**Comment by sabitovvt** [comment]
In version 1.2.0
Added setting favoritesPanel.commandsForWorkspace
Added setting favoritesPanel.configPathForWorkspace
