### ISSUE TITLE
Does not open image from computer

### ISSUE THREAD

**Issue by LeninZapata** [sabitovvt/vscode-favorites-panel#2]
Hello, I want to open an image, this is the correct path copied from the folder path and the file successfully, but I get a message as if the file does not exist. Something that I am doing wrong? I use Win10
```
{
	"label": "Inspiracion",
	"description": "la bebe",
	"command": "openFile",
	"arguments": ["C:\\Users\\LZP\\Documents\\ShareX\\Screenshots\\2021-04\\collagesashamot.jpg", "external"]
},
```

**Comment by sabitovvt** [comment]
Opening images is not supported in the VS Code Extension API

**Comment by LeninZapata** [comment]
I hope it can be solved in the future, it is only about opening an image type file, I do not see it so complicated but if the API does not allow it it is fine.
