### ISSUE TITLE
Refresh Panel and reading settings from settings.json are broken in 0.11

### ISSUE THREAD

**Issue by egrinant** [sabitovvt/vscode-favorites-panel#6]
Refresh Panel doesn't work, It doesn't seem to raise any error in the UI.

Settings are not being read from `settings.json`, instead it's only reading `demosettings.json` file.

In case you may wonder if its due to my settings.json:

- If I copy the config from my `settings.json` `favoritesPanel.commands` to the `demosettings.json` file, it does work.
- Erasing eveything in `settings.json` and putting a simple command in `settings.json` will fall back to `demosettings.json` anyway.

**Comment by sabitovvt** [comment]
Fixed loading settings for use cases without opening a folder  in version 0.11.1
