### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [sabitovvt/vscode-favorites-panel#9]
The [Open VSX Registry](https://open-vsx.org/?search=favorites) has currently no extension to group files or commands.

Open VSX Registry is the default extension provider endpoint for the free build of vscode VSCodium and Eclipse Theia. It would be nice to have this extension be directly published to a free vsix repository instead of only the Microsoft Marketplace with its restrictions.
 
Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions which also has info about a GH action that would publish extensions to both market places so only the initial setup would be necessary.

**Comment by sabitovvt** [comment]
https://open-vsx.org/extension/sabitovvt/favorites-panel
